### ISSUE TITLE
Validate link format

### ISSUE THREAD

**Issue by poteto** [poteto/hiring-without-whiteboards#402]
For example, like https://github.com/vhf/remark-lint-books-links

**Comment by wooorm** [comment]
Hi! 👋

Thanks for thinking of remark! To start, do you have examples of valid and non-valid examples of links?

**Comment by poteto** [comment]
Hi! For a bit of context, I am parsing the GitHub diffs via this simple [node API](https://github.com/poteto/hww-api) that I quickly put together a few days ago. Then I push the various bits of data into an [Airtable](https://airtable.com/shr5TdnpVYVTpeRrN/tbluCbToxQ2knSLhh) via its API.

The main issue I'm having is just validating that locations adhere to a [format](https://github.com/poteto/hiring-without-whiteboards/blob/master/CONTRIBUTING.md#format), for example if someone uses the following:

```md
-[MyCo](http://example.com) | San Francisco, London, Tokyo, Japan, US | 
```

It makes it very difficult for me to programmatically figure out what city/country these are. The "good" format would be:

```md
-[MyCo](http://example.com) | San Francisco, CA; London, UK; Tokyo, Japan & Remote | 
```

**Comment by wooorm** [comment]
Thanks for the background info!

As an initial example implementation idea: would it work if we split on the delimiters (`/`, `;`, `&`), and check if any resulting part contains more than one comma?

That way, `San Francisco, London, Tokyo, Japan, US` would warn, as it contains multiples commas in its (one and only) part?

`San Francisco, CA; London, UK; Tokyo, Japan & Remote` would not warn as all parts (`'San Francisco, CA', 'London, UK', 'Tokyo, Japan', 'Remote`) contain zero or one comma?

**Comment by poteto** [comment]
That _could_ work, but if you include the state then it would be a false negative since I'm using the google maps places API and it is pretty flexible with what you throw at it:

```
✅  San Francisco, CA, USA 
```

It might be a good first try though! I can always update the format to tell people to not use more than 2 commas xD

Eg

```
San Francisco, CA
```

OR

```
San Francisco, USA
```

**Comment by wooorm** [comment]
Well a list of US states is [available](https://www.npmjs.com/package/datasets-us-states-abbr)!
How about the previously mentioned “algorithm”, with support for US state abbreviations as an exception?

**Comment by wooorm** [comment]
Oh and thank you, I appreciate it, and: no problem :)

**Comment by wooorm** [comment]
OK, I didn't test this, but I think this will work, could you give it a spin?

```js
var rule = require('unified-lint-rule');
var generated = require('unist-util-generated');
var visit = require('unist-util-visit');
var toString = require('mdast-util-to-string');
var states = require('datasets-us-states-abbr');

module.exports = rule('remark-lint:hww-list-items', item);

function item(tree, file) {
  visit(tree, 'listItem', visitor);
  
  function visitor(node, index, parent) {
    var head;
    var link;
    var rest;
    var places;
    var description;
    var parts;

    if (parent.ordered || generated(node)) {
      return;
    }

    head = node.children[0];
    link = head && head.children && head.children[0];

    if (!link || link.type !== 'link' || head.children.length === 1) {
      return;
    }

    rest = toString({children: head.children.slice(1)})
      .replace(/^\s*\|\s*/, '')
      .split(/\s*\|\s*/);

    places = rest[0];
    // description = rest[1];

    if (rest.length > 2) {
      file.message('Too many pipes, expected ` | places | description` after link', node);
      return;
    }

    places.split(/\s*[/;&]\s*/g).forEach(checkPlace);

    function checkPlace(place) {
      var parts = place.split(/\s*,\s*/);
      var state = parts[1] && states.indexOf(parts[1].toUpperCase());
      var max = state ? 3 : 2;

      if (parts.length > max) {
        file.message(
          'Too many parts in place `' + place[0] + '`, use commas in places ' +
          'but semicolons between them: `city, country; city, state, country`',
          node
        );
      }
    }
  }
}
```

...names and warning messages are quickly though-up!

**Comment by poteto** [comment]
This is great ❤️ Thanks so much for the help! I'll give it a try and let you know

**Comment by poteto** [comment]
@wooorm With a tiny bit of adjustment, it works! https://github.com/poteto/remark-lint-hiring-without-whiteboards-links

Now I have to correct all the previous entries... 😅 Thanks for the help!

**Comment by wooorm** [comment]
Awesome! No probz!

**Comment by wooorm** [comment]
Ha, nice timing :)
